name: local_settings_api
description: Simple local settings API using SharedPreferences
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: 
  shared_preferences: ^2.0.15

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1

