name: launch_repository
description: A Dart package that manages the rocket launch domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  filtered_repository:
    path: ../filtered_repository
  local_settings_api:
    path: ../local_settings_api
  spacex_api:
    path: ../spacex_api

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
