name: launch_repository
description: A Dart package that manages the rocket launch domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  filtered_repository:
    path: ../filtered_repository
  json_annotation: ^4.6.0
  local_settings_api:
    path: ../local_settings_api
  spacex_api:
    path: ../spacex_api

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
