name: spacex_ui
description: A collection of widgets used across the SpaceX app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
