name: filter_repository
description: A Dart package that manages the filter domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: 
  equatable: ^2.0.3
  hive: ^2.2.3

dev_dependencies:
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
